source 'https://github.com/CocoaPods/Specs.git'
source 'http://120.55.72.192/ios/DNSpecs.git'
use_frameworks!

target 'DnpTool_Example' do
  pod 'DnpTool', :path => '../'
  pod 'ZLNetworkComponent'

  target 'DnpTool_Tests' do
    inherit! :search_paths

    
  end
end
